#!/bin/tcsh
#
module purge
module load cmake/3.8
module load gnu/7.3.1
module load sierra-devel/intel-18.0.5-openmpi-2.1

./configure --intel --with-mpi --prefix="."  \
\
  |& tee OUTPUT.CONFIG
make |& tee OUTPUT.MAKE
make install
